import { NextResponse } from "next/server";

const data = [
  "newyork",
  "Tokyo",
  "Swimming",
  "Paris",
  "Hiking",
  "London",
  "Running",
  "rome",
  "palce",
  "Sydney",
  "Basketball",
  "Rome",
  "Yoga",
  "Amsterdam",
  "Dancing",
  "Toronto",
  "Football",
  "Los Angeles",
  "restaurant",
  "automobile",
  "Skiing",
  "Madrid",
  "Tennis",
  "Vienna",
  "Soccer",
  "Moscow",
  "Climbing",
  "Dubai",
  "Reading",
  "San Francisco",
  "Painting",
  "Chicago",
  "Cooking",
  "Mexico City",
  "Fishing",
  "food",
  "Photography",
  "Hong Kong",
  "Gardening",
  "Istanbul",
  "Sailing",
  "Seoul",
  "Surfing",
  "newyork",
  "Running",
  "Paris",
  "Yoga",
  "rome",
  "palce",
  "Rome",
  "Football",
  "Tokyo",
  "Hiking",
  "London",
  "Swimming",
  "Amsterdam",
  "Basketball",
  "Toronto",
  "Dancing",
  "Madrid",
  "restaurant",
  "Vienna",
  "Tennis",
  "Los Angeles",
  "Soccer",
  "automobile",
  "Climbing",
  "Dubai",
  "Reading",
  "San Francisco",
  "Cooking",
  "Chicago",
  "Painting",
  "Mexico City",
  "Fishing",
  "food",
  "Photography",
  "Hong Kong",
  "Gardening",
  "Istanbul",
  "Sailing",
  "Seoul",
  "Surfing",
  "newyork",
  "Running",
  "Paris",
  "Yoga",
  "rome",
  "palce",
  "Rome",
  "Football",
  "Tokyo",
  "Hiking",
  "London",
  "Swimming",
];

export async function POST(req: Request) {
    const { activity, location } = await req.json();
  
    await new Promise((resolve) => setTimeout(resolve, 2000));
  
    const filteredData = data.filter(
      (x) =>
        (activity && x.toLowerCase().includes(activity.toLowerCase())) ||
        (location && x.toLowerCase().includes(location.toLowerCase()))
    );
  
    return NextResponse.json({ data: filteredData });
  }
