import { NextResponse } from "next/server";
const exploreData = [
  {
    id: 1,
    image: "/explore/e1.jpg",
    title: "Discover Hidden Gems",
    rating: 4.5,
    totalRating: 27,
    color: "#00bfff",
    category: "Travel",
    open: true,
    avatar: "/clients/c1.png",
    range: "5k$ - 12k$",
    description: "Explore the hidden gems of the city and discover new places.",
  },
  {
    id: 2,
    image: "/explore/e2.jpg",
    title: "Gastronomic Delights",
    rating: 4.7,
    totalRating: 35,
    color: "#ffff00",
    category: "Food",
    open: false,
    avatar: "/clients/c2.png",
    range: "3k$ - 8k$",
    description: "Taste the best dishes from top chefs around the world.",
  },
  {
    id: 3,
    image: "/explore/e3.jpg",
    title: "Cultural Expeditions",
    rating: 5.0,
    totalRating: 42,
    color: "#008000",
    category: "Culture",
    open: true,
    avatar: "/clients/c3.png",
    range: "10k$ - 20k$",
    description: "Immerse yourself in diverse cultures and traditions.",
  },
  {
    id: 4,
    image: "/explore/e4.jpg",
    title: "Adventure Trails",
    rating: 4.2,
    totalRating: 50,
    color: "#ff6347",
    category: "Adventure",
    open: true,
    avatar: "/clients/c4.png",
    range: "15k$ - 30k$",
    description: "Join thrilling adventure trails and test your limits.",
  },
  {
    id: 5,
    image: "/explore/e5.jpg",
    title: "Historic Sites",
    rating: 4.8,
    totalRating: 22,
    color: "#ffa500",
    category: "History",
    open: false,
    avatar: "/clients/c1.png",
    range: "8k$ - 25k$",
    description: "Visit historic sites and learn about the rich past.",
  },
  {
    id: 6,
    image: "/explore/e6.jpg",
    title: "Urban Exploration",
    rating: 4.9,
    totalRating: 60,
    color: "#ff69b4",
    category: "Urban",
    open: true,
    avatar: "/clients/c2.png",
    range: "12k$ - 45k$",
    description: "Explore urban areas and uncover hidden urban gems.",
  },
];
export async function GET() {
  await new Promise((resolve) => setTimeout(resolve, 3000));

  return NextResponse.json(exploreData);
}
